config/routes.rb
HasMediaExample::Application.routes.draw do
  resources :directories

  resources :media, :only => [:destroy]

  root :to => "directories#index"

end

app/models/audio.rb
class Audio < Medium
  mount_uploader :file, AudioUploader
  after_save :enqueue_encoding

  private 

  def enqueue_encoding
    Resque.enqueue(EncodeAudio, File.join(self.original_file_path))
  end 
end

app/models/avatar.rb
class Avatar < Medium
  mount_uploader :file, AvatarUploader
end

app/models/directory.rb
class Directory < ActiveRecord::Base
  has_one_medium :avatar, :only => :avatar
  has_many_media :images, :only => :image
  has_many_media :audios, :only => :audio
  has_many_media :videos, :only => :video
  validates_presence_of :title
end

app/models/image.rb
class Image < Medium
  mount_uploader :file, ImageUploader
  after_save :enqueue_encoding

  private 

  def enqueue_encoding
    Resque.enqueue(EncodeImage, File.join(self.original_file_path))
  end 
end

app/models/video.rb
class Video < Medium
  mount_uploader :file, VideoUploader
  after_save :enqueue_encoding

  private 

  def enqueue_encoding
    Resque.enqueue(EncodeVideo, File.join(self.original_file_path))
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  # GET /directories
  # GET /directories.xml
  def index
    @directories = Directory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @directories }
    end
  end

  # GET /directories/1
  # GET /directories/1.xml
  def show
    @directory = Directory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @directory }
    end
  end

  # GET /directories/new
  # GET /directories/new.xml
  def new
    @directory = Directory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @directory }
    end
  end

  # GET /directories/1/edit
  def edit
    @directory = Directory.find(params[:id])
  end

  # POST /directories
  # POST /directories.xml
  def create
    @directory = Directory.new(params[:directory])

    respond_to do |format|
      if @directory.save
        format.html { redirect_to(@directory, :notice => 'Directory was successfully created.') }
        format.xml  { render :xml => @directory, :status => :created, :location => @directory }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @directory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /directories/1
  # PUT /directories/1.xml
  def update
    @directory = Directory.find(params[:id])

    respond_to do |format|
      if @directory.update_attributes(params[:directory])
        format.html { redirect_to(@directory, :notice => 'Directory was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @directory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /directories/1
  # DELETE /directories/1.xml
  def destroy
    @directory = Directory.find(params[:id])
    @directory.destroy

    respond_to do |format|
      format.html { redirect_to(directories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directories/_form.html.erb
<%= form_for(@directory, :html => {:multipart => true}) do |f| %>
  <% if @directory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directory.errors.count, "error") %> prohibited this directory from being saved:</h2>

      <ul>
      <% @directory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </p>

  <fieldset>
    <legend>Avatar</legend>
    <%= has_media_field @directory, :avatar %>
  </fieldset>

  <fieldset>
    <legend>Images</legend>
    <%= has_media_field @directory, :images %>
  </fieldset>

  <fieldset>
    <legend>Audios</legend>
    <%= has_media_field @directory, :audios %>
  </fieldset>

  <fieldset>
    <legend>Videos</legend>
    <%= has_media_field @directory, :videos %>
  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directories/edit.html.erb
<h1>Editing directory</h1>

<%= render 'form' %>

<%= link_to 'Show', @directory %> |
<%= link_to 'Back', directories_path %>

app/views/directories/index.html.erb
<h1>Listing directories</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @directories.each do |directory| %>
  <tr>
    <td><%= directory.title %></td>
    <td><%= link_to 'Show', directory %></td>
    <td><%= link_to 'Edit', edit_directory_path(directory) %></td>
    <td><%= link_to 'Destroy', directory, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Directory', new_directory_path %>

app/views/directories/new.html.erb
<h1>New directory</h1>

<%= render 'form' %>

<%= link_to 'Back', directories_path %>

app/views/directories/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h1><%= @directory.title %></h1>

  <fieldset>
    <legend>Avatar (CarrierWave & RMagick encoded)</legend>
    <%- unless @directory.avatar.nil? %>
      <h2><%= @directory.avatar.filename %></h2>
    <%- end %>
    thumb :<%= image_tag @directory.avatar.file_url(:thumb) %>
    thumb sepia :<%= image_tag @directory.avatar.file_url(:thumb_sepia) %>
  </fieldset>

  <fieldset>
    <legend>Images (Resque & RMagick encoded)</legend>
    <%- @directory.images.each do |image| %>
      <h2><%= image.filename %></h2>
      crop_200 :<%= image_tag image.file_uri(:crop_200) %>
      fill_200 :<%= image_tag image.file_uri(:fill_200) %>
    <%- end %>
  </fieldset>

  <fieldset>
    <legend>Audios (Resque & ffmpeg encoded)</legend>
    <%- @directory.audios.each do |audio| %>
      <h2><%= audio.filename %></h2>
      re encoded :
      <audio controls="controls" preload="true">
        <source src="<%= audio.file_uri(:encoded) %>" />
        You browser does not support HTML5
      </audio>
    <%- end %>
  </fieldset>

  <fieldset>
    <legend>Videos (Resque & ffmpeg encoded)</legend>
    <%- @directory.videos.each do |video| %>
      <h2><%= video.filename %></h2>
      re encoded :
      <video controls="controls" preload="true">
        <source src="<%= video.file_uri(:encoded) %>" />
        You browser does not support HTML5
      </video>
    <%- end %>
  </fieldset>

</div>

<%= link_to 'Edit', edit_directory_path(@directory) %> |
<%= link_to 'Back', directories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HasMediaExample</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>